name: 'action-tag-commit'
description: A GitHub Action which creates a git tag in a repository for a commit
inputs:
  repo-name:
    description: 'Repository name to create tag'
    required: true
  commit-sha:
    description: 'Commit SHA to tag'
    required: true
  organization:
    description: 'GitHub organization name'
    required: true
  tag-name:
    description: 'Tag to add to the repository'
    required: true
  token:
    description: 'GitHub Token or PAT'
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - run: 'cp ${{ github.action_path }}/requirements.txt .'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: make install
      shell: bash
      working-directory: ${{ github.action_path }}
    - run: python ${{ github.action_path }}/main.py
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        REPO_NAME: ${{ inputs.repo-name }}
        COMMIT_SHA: ${{ inputs.commit-sha }}
        ORGANIZATION: ${{ inputs.organization }}
        TOKEN: ${{ inputs.token }}
        TAG_NAME: ${{ inputs.tag-name }}
